create_clock -period 5.000 -name sysclk [get_ports sysclk_p]
create_clock -period 12.500 -name syncclk [get_ports SYNC_P]

#DPo fix
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets sync]
#end DPO fix


#set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins Infra/clocks/mmcm/CLKOUT1]] -group [get_clocks -of_objects [get_pins IPbus_slaves/TRIGGERING/BUFR_inst/O]]

set_false_path -from [get_pins Infra/clocks/rst_reg/C] -to [get_pins Infra/clocks/rst_ipb_reg/D]
set_false_path -from [get_pins Infra/clocks/rst_reg/C] -to [get_pins Infra/clocks/rst_ipb_ctrl_reg/D]
set_false_path -from [get_pins Infra/clocks/rst_reg/C] -to [get_pins Infra/clocks/rst_125_reg/D]

#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets USER_SMA_GPIO_N_IBUF]

set_false_path -from [get_clocks -of_objects [get_pins Infra/clocks/mmcm/CLKOUT1]] -to [get_pins IPbus_slaves/DOUT4/rst_syn1_reg/D]
#set_false_path -from [get_clocks -of_objects [get_pins Infra/clocks/mmcm/CLKOUT1]] -to [get_clocks -of_objects [get_pins IPbus_slaves/TRIGGERING/BUFR_inst/O]]


# Input Delay Constraint 1
set_input_delay -clock syncclk -max 6.750 [get_ports {{READOUT_P[0]} {READOUT_P[1]} {READOUT_P[2]} {READOUT_P[3]} {READOUT_P[4]} {READOUT_P[5]} {READOUT_P[6]} {READOUT_P[7]}}]
set_input_delay -clock syncclk -min 5.750 [get_ports {{READOUT_P[0]} {READOUT_P[1]} {READOUT_P[2]} {READOUT_P[3]} {READOUT_P[4]} {READOUT_P[5]} {READOUT_P[6]} {READOUT_P[7]}}]
set_input_delay -clock syncclk -clock_fall -max -add_delay 6.750 [get_ports {{READOUT_P[0]} {READOUT_P[1]} {READOUT_P[2]} {READOUT_P[3]} {READOUT_P[4]} {READOUT_P[5]} {READOUT_P[6]} {READOUT_P[7]}}]
set_input_delay -clock syncclk -clock_fall -min -add_delay 5.750 [get_ports {{READOUT_P[0]} {READOUT_P[1]} {READOUT_P[2]} {READOUT_P[3]} {READOUT_P[4]} {READOUT_P[5]} {READOUT_P[6]} {READOUT_P[7]}}]


# Input Delay Constraint readout 2
set_input_delay -clock syncclk -max 6.750 [get_ports {{READOUT2_P[0]} {READOUT2_P[1]} {READOUT2_P[2]} {READOUT2_P[3]} {READOUT2_P[4]} {READOUT2_P[5]} {READOUT2_P[6]} {READOUT2_P[7]}}]
set_input_delay -clock syncclk -min 5.750 [get_ports {{READOUT2_P[0]} {READOUT2_P[1]} {READOUT2_P[2]} {READOUT2_P[3]} {READOUT2_P[4]} {READOUT2_P[5]} {READOUT2_P[6]} {READOUT2_P[7]}}]
set_input_delay -clock syncclk -clock_fall -max -add_delay 6.750 [get_ports {{READOUT2_P[0]} {READOUT2_P[1]} {READOUT2_P[2]} {READOUT2_P[3]} {READOUT2_P[4]} {READOUT2_P[5]} {READOUT2_P[6]} {READOUT2_P[7]}}]
set_input_delay -clock syncclk -clock_fall -min -add_delay 5.750 [get_ports {{READOUT2_P[0]} {READOUT2_P[1]} {READOUT2_P[2]} {READOUT2_P[3]} {READOUT2_P[4]} {READOUT2_P[5]} {READOUT2_P[6]} {READOUT2_P[7]}}]

# Input Delay Constraint readout 3
set_input_delay -clock syncclk -max 6.750 [get_ports {{READOUT3_P[0]} {READOUT3_P[1]} {READOUT3_P[2]} {READOUT3_P[3]} {READOUT3_P[4]} {READOUT3_P[5]} {READOUT3_P[6]} {READOUT3_P[7]}}]
set_input_delay -clock syncclk -min 5.750 [get_ports {{READOUT3_P[0]} {READOUT3_P[1]} {READOUT3_P[2]} {READOUT3_P[3]} {READOUT3_P[4]} {READOUT3_P[5]} {READOUT3_P[6]} {READOUT3_P[7]}}]
set_input_delay -clock syncclk -clock_fall -max -add_delay 6.750 [get_ports {{READOUT3_P[0]} {READOUT3_P[1]} {READOUT3_P[2]} {READOUT3_P[3]} {READOUT3_P[4]} {READOUT3_P[5]} {READOUT3_P[6]} {READOUT3_P[7]}}]
set_input_delay -clock syncclk -clock_fall -min -add_delay 5.750 [get_ports {{READOUT3_P[0]} {READOUT3_P[1]} {READOUT3_P[2]} {READOUT3_P[3]} {READOUT3_P[4]} {READOUT3_P[5]} {READOUT3_P[6]} {READOUT3_P[7]}}]

# Input Delay Constraint readout 4
set_input_delay -clock syncclk -max 6.750 [get_ports {{READOUT4_P[0]} {READOUT4_P[1]} {READOUT4_P[2]} {READOUT4_P[3]} {READOUT4_P[4]} {READOUT4_P[5]} {READOUT4_P[6]} {READOUT4_P[7]}}]
set_input_delay -clock syncclk -min 5.750 [get_ports {{READOUT4_P[0]} {READOUT4_P[1]} {READOUT4_P[2]} {READOUT4_P[3]} {READOUT4_P[4]} {READOUT4_P[5]} {READOUT4_P[6]} {READOUT4_P[7]}}]
set_input_delay -clock syncclk -clock_fall -max -add_delay 6.750 [get_ports {{READOUT4_P[0]} {READOUT4_P[1]} {READOUT4_P[2]} {READOUT4_P[3]} {READOUT4_P[4]} {READOUT4_P[5]} {READOUT4_P[6]} {READOUT4_P[7]}}]
set_input_delay -clock syncclk -clock_fall -min -add_delay 5.750 [get_ports {{READOUT4_P[0]} {READOUT4_P[1]} {READOUT4_P[2]} {READOUT4_P[3]} {READOUT4_P[4]} {READOUT4_P[5]} {READOUT4_P[6]} {READOUT4_P[7]}}]







set_property MARK_DEBUG false [get_nets {IPbus_slaves/hit_mask[59]}]
set_property MARK_DEBUG false [get_nets {IPbus_slaves/hit_mask[62]}]
set_property MARK_DEBUG false [get_nets {IPbus_slaves/hit_mask[63]}]
set_property MARK_DEBUG false [get_nets {IPbus_slaves/hit_mask[15]}]
set_property MARK_DEBUG false [get_nets {IPbus_slaves/hit_mask[11]}]
set_property MARK_DEBUG false [get_nets {IPbus_slaves/hit_mask[6]}]
set_property MARK_DEBUG false [get_nets {IPbus_slaves/hit_mask[0]}]
set_property MARK_DEBUG false [get_nets {IPbus_slaves/hit_mask[1]}]
set_property MARK_DEBUG false [get_nets {IPbus_slaves/hit_mask[44]}]
set_property MARK_DEBUG false [get_nets {IPbus_slaves/hit_mask[46]}]
set_property MARK_DEBUG false [get_nets {IPbus_slaves/hit_mask[43]}]
set_property MARK_DEBUG false [get_nets {IPbus_slaves/hit_mask[30]}]
set_property MARK_DEBUG false [get_nets {IPbus_slaves/hit_mask[34]}]
set_property MARK_DEBUG false [get_nets {IPbus_slaves/hit_mask[16]}]
set_property MARK_DEBUG false [get_nets {IPbus_slaves/hit_mask[54]}]
set_property MARK_DEBUG false [get_nets {IPbus_slaves/hit_mask[17]}]
set_property MARK_DEBUG false [get_nets {IPbus_slaves/hit_mask[14]}]
set_property MARK_DEBUG false [get_nets {IPbus_slaves/hit_mask[38]}]
set_property MARK_DEBUG false [get_nets {IPbus_slaves/hit_mask[3]}]
set_property MARK_DEBUG false [get_nets {IPbus_slaves/hit_mask[4]}]
set_property MARK_DEBUG false [get_nets {IPbus_slaves/hit_mask[32]}]
set_property MARK_DEBUG false [get_nets {IPbus_slaves/hit_mask[5]}]
set_property MARK_DEBUG false [get_nets {IPbus_slaves/hit_mask[24]}]
set_property MARK_DEBUG false [get_nets {IPbus_slaves/hit_mask[20]}]
set_property MARK_DEBUG false [get_nets {IPbus_slaves/hit_mask[41]}]
set_property MARK_DEBUG false [get_nets {IPbus_slaves/hit_mask[7]}]
set_property MARK_DEBUG false [get_nets {IPbus_slaves/hit_mask[8]}]
set_property MARK_DEBUG false [get_nets {IPbus_slaves/hit_mask[39]}]
set_property MARK_DEBUG false [get_nets {IPbus_slaves/hit_mask[23]}]
set_property MARK_DEBUG false [get_nets {IPbus_slaves/hit_mask[50]}]
set_property MARK_DEBUG false [get_nets {IPbus_slaves/hit_mask[19]}]
set_property MARK_DEBUG false [get_nets {IPbus_slaves/hit_mask[55]}]
set_property MARK_DEBUG false [get_nets {IPbus_slaves/hit_mask[56]}]
set_property MARK_DEBUG false [get_nets {IPbus_slaves/hit_mask[57]}]
set_property MARK_DEBUG false [get_nets {IPbus_slaves/hit_mask[58]}]
set_property MARK_DEBUG false [get_nets {IPbus_slaves/hit_mask[60]}]
set_property MARK_DEBUG false [get_nets {IPbus_slaves/hit_mask[61]}]
set_property MARK_DEBUG false [get_nets {IPbus_slaves/hit_mask[2]}]
set_property MARK_DEBUG false [get_nets {IPbus_slaves/hit_mask[28]}]
set_property MARK_DEBUG false [get_nets {IPbus_slaves/hit_mask[45]}]
set_property MARK_DEBUG false [get_nets {IPbus_slaves/hit_mask[35]}]
set_property MARK_DEBUG false [get_nets {IPbus_slaves/hit_mask[49]}]
set_property MARK_DEBUG false [get_nets {IPbus_slaves/hit_mask[53]}]
set_property MARK_DEBUG false [get_nets {IPbus_slaves/hit_mask[47]}]
set_property MARK_DEBUG false [get_nets {IPbus_slaves/hit_mask[31]}]
set_property MARK_DEBUG false [get_nets {IPbus_slaves/hit_mask[18]}]
set_property MARK_DEBUG false [get_nets {IPbus_slaves/hit_mask[52]}]
set_property MARK_DEBUG false [get_nets {IPbus_slaves/hit_mask[29]}]
set_property MARK_DEBUG false [get_nets {IPbus_slaves/hit_mask[40]}]
set_property MARK_DEBUG false [get_nets {IPbus_slaves/hit_mask[48]}]
set_property MARK_DEBUG false [get_nets {IPbus_slaves/hit_mask[51]}]
set_property MARK_DEBUG false [get_nets {IPbus_slaves/hit_mask[33]}]
set_property MARK_DEBUG false [get_nets {IPbus_slaves/hit_mask[25]}]
set_property MARK_DEBUG false [get_nets {IPbus_slaves/hit_mask[22]}]
set_property MARK_DEBUG false [get_nets {IPbus_slaves/hit_mask[21]}]
set_property MARK_DEBUG false [get_nets {IPbus_slaves/hit_mask[36]}]
set_property MARK_DEBUG false [get_nets {IPbus_slaves/hit_mask[37]}]
set_property MARK_DEBUG false [get_nets {IPbus_slaves/hit_mask[9]}]
set_property MARK_DEBUG false [get_nets {IPbus_slaves/hit_mask[27]}]
set_property MARK_DEBUG false [get_nets {IPbus_slaves/hit_mask[42]}]
set_property MARK_DEBUG false [get_nets {IPbus_slaves/hit_mask[26]}]
set_property MARK_DEBUG false [get_nets {IPbus_slaves/hit_mask[10]}]
set_property MARK_DEBUG false [get_nets {IPbus_slaves/hit_mask[12]}]
set_property MARK_DEBUG false [get_nets {IPbus_slaves/hit_mask[13]}]



set_property MARK_DEBUG false [get_nets IPbus_slaves/TRIGGERING/rise_external]
set_property MARK_DEBUG false [get_nets IPbus_slaves/TRIGGERING/rise_circular]
set_property MARK_DEBUG false [get_nets IPbus_slaves/TRIGGERING/rise_start]
set_property MARK_DEBUG false [get_nets IPbus_slaves/TRIGGERING/rise_clear]
set_property MARK_DEBUG false [get_nets IPbus_slaves/TRIGGERING/trigger]
set_property MARK_DEBUG true [get_nets trigger]
set_property MARK_DEBUG true [get_nets clk_trigger]

set_property FIXED_ROUTE { { LIOI_ODELAY0_DATAOUT LIOI_O0 IOB_O_OUT0 IOB_O_IN1 }  } [get_nets IPbus_slaves/TRIGGERING/hit_trigger]
set_property BEL A6LUT [get_cells {u_ila_0/inst/ila_core_inst/shifted_data_in_reg[7][0]_srl8}]
set_property BEL B6LUT [get_cells {u_ila_0/inst/ila_core_inst/u_trig/U_TM/N_DDR_MODE.G_NMU[0].U_M/allx_typeA_match_detection.ltlib_v1_0_0_allx_typeA_inst/probeDelay1[0]_i_1}]
set_property LOC SLICE_X100Y37 [get_cells {u_ila_0/inst/ila_core_inst/shifted_data_in_reg[7][0]_srl8}]
set_property LOC SLICE_X93Y43 [get_cells {u_ila_0/inst/ila_core_inst/u_trig/U_TM/N_DDR_MODE.G_NMU[0].U_M/allx_typeA_match_detection.ltlib_v1_0_0_allx_typeA_inst/probeDelay1[0]_i_1}]
set_property LOC ODELAY_X0Y226 [get_cells IPbus_slaves/TRIGGERING/ODELAYE2_inst]
set_property LOC AD40 [get_cells OBUF_CLK_1]
set_property PACKAGE_PIN AD40 [get_ports TEST_1_P]
set_property PACKAGE_PIN AD41 [get_ports TEST_1_N]
set_property MARK_DEBUG true [get_nets IPbus_slaves/TRIGGERING/hit_trigger_tmp]
connect_debug_port u_ila_0/clk [get_nets [list u_ila_0_clock_out]]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_clock_out]

set_property MARK_DEBUG true [get_nets hit_trigger]
set_property MARK_DEBUG false [get_nets I]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list Infra/clocks/mmcm_0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 1 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list clk_trigger]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list hit_trigger]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list reset_bx]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list reset_eid]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list IPbus_slaves/TRIGGERING/clock_out]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 1 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list trigger]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_1_clock_out]
